name: Deploy to GitHub Pages
description: Deploy site to GitHub Pages
runs:
  using: "composite"
  steps:
    - name: Deploy
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add build
        git commit -m "Deploy to GitHub Pages"
        git push origin gh-pages
