name: Setup Python
description: Setup Python environment
runs:
  using: "composite"
  steps:
    - name: Set up Python
      run: |
        sudo apt-get install python3
        sudo apt-get install python3-pip
        python3 -m pip install --upgrade pip
