name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: ./.github/actions/checkout

    - name: Set up Python
      uses: ./.github/actions/setup-python

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install sphinx furo

    - name: Build documentation
      run: sphinx-build -b html source build

    - name: Deploy to GitHub Pages
      uses: ./.github/actions/gh-pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
